<div class="pagecontent">
<div class="columnblock">
<div class="column1">
	<div class="bannerblocknormal">Privacy Statement</div>
	<div class="column1block">
		<p class="contenthead">Privacy Statement</p>
		<p class="contenttext">At VMC Technologies Private Limited ("VMC" we take the right to privacy seriously. We value the confidentiality of the information which you provide when registering through our website.</p>
		<p class="contenttext">The following sets forth the privacy policies and practices for this Web site operated by VMC Technologies Private Limited and located at http://www.vmc.in. This agreement supersedes any previous statement and policies. Throughout these Terms, the word .Site. is used to refer to this Web site. VMC Technologies may modify, alter or update these Terms at any time without prior notice, and your subsequent use of the Site shall constitute your consent to the modification, alteration or update.</p>
		<p class="contenttext">Please read the following to learn what information we collect from you (the "User" or the "End User") and how we use that information. If you have any questions about our privacy policy, please email us at <span class="txtlinkA"><a href="mailto:support@vmc.in">support@vmc.in</a></span></p>
		<p class="contenttext">PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY ACCESSING OR USING OUR WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND TO ALL THE TERMS OF THIS PRIVACY POLICY AND OUR WEBSITE TERMS OF USE. IF YOU DO NOT AGREE TO THESE TERMS, EXIT THIS PAGE AND DO NOT ACCESS OR USE THE <span class="txtlinkA"><a href="http://www.vmc.in">vmc.in</a></span> WEBSITE OR ANY OF ITS SUBDOMAINS.</p>
		<p class="contentsubhead">1. Changes to Privacy Policy</p>
		<p class="contenttext">Any future changes to policy will be posted to this privacy statement, the home page, and other places we deem appropriate so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we disclose it.</p>
		<p class="contenttext">We reserve the right to modify this privacy statement at any time, so please review it frequently. </p>
		<p class="contentsubhead">2. Types of Information Collected and Uses of Collected Information</p>
		<p class="contenttext">We collect two types of information about our Website Users: Personal Information and Non-Personal Information. </p>
		<p class="contenttext"><strong>Personal Information</strong>. Personal Information is information that identifies a specific End User. When you engage in certain activities on the Website, such as creating an account, ordering a product or service from us or our partners, submitting content and/or posting content in discussion forums, entering a contest or sweepstakes sponsored by us or our partners, filling out a survey, posting a review, sending us or our partners feedback, requesting information about our services, submitting an affiliate agreement, applying for a job, posting a video or signing up for special offers from third parties through the Website (collectively, "Identification Activities"), we may ask you to provide certain information about yourself. It is optional for you to engage in an Identification Activity. If you elect to engage in an Identification Activity, however, we may ask you to provide us with certain personal information about yourself, such as your first and last name, mailing address (including zip code), email address, telephone number and date of birth. When you order products or services, we may also ask you to provide us with your credit card number, expiration date and authentication codes or related information. Depending on the activity, some of the information we ask you to provide is identified as mandatory and some is identified as voluntary. If you do not provide the mandatory information for a particular activity that requires it, you will not be permitted to engage in that activity</p>
		<p class="contenttext"><strong>Tell-A-Friend</strong>. If you choose to use our referral service, we will ask you for your friend's name, email address and phone number. We will automatically send your friend a one-time email and  SMS with the invitation to visit the site. VMC stores this information for the sole purpose of sending this email, SMS, and tracking the success of our referral program.</p>
		<p class="contenttext">Your friend may contact us at  <span class="txtlinkA"><a href="mailto:support@vmc.in">support@vmc.in</a></span> to request that we remove this information from our database.</p>
		<p class="contenttext">We use Personal Information to provide products and services to you, administer sweepstakes and contests, enhance the operation of the Website, improve our marketing and promotional efforts, analyze Website use, improve our product and service offerings, and to tailor your experience with third parties as provided in Item 3 of this Privacy Policy. For example, if you send our customer service an email we may use your comments and feedback to tell others about our services, and may post your comment in our marketing materials or on our Website. Your comments may contain personal information such as your name, we will obtain consent from you to post your name along with your comment prior to posting your comment for public view. In addition, if you use our Website to send information or a product to another person, we may store your personal information. We may also use Personal Informationto troubleshoot, resolve disputes, accomplish administrative tasks, contact you, enforce our agreements with you, including our Website Terms of Use and this Privacy Policy, comply with applicable law, and cooperate with law enforcement activities. </p>
		<p class="contenttext"><strong>Non-Personal Information</strong>. Non-Personal Information is information that does not identify a specific End User. This type of information may include things like the Uniform Resource Locator ("URL") of the website you visited before coming to our Website, the URL of the website you visit after leaving our Website, the type of browser you are using and your Internet Protocol ("IP") address. We, and/or our authorized Third Party Service Providers and Advertisers, may automatically collect this information when you visit our Website through the use of electronic tools like Cookies.</p>
		<p class="contenttext">We use Non-Personal Information to troubleshoot, administer the Website, analyze trends, gather demographic information, comply with applicable law, and cooperate with law enforcement activities. We may also share this information with our authorized Third Party Service Providers and Advertisers to measure the overall effectiveness of our online advertising, content, and programming. </p>
		<p class="contentsubhead">3. Release of Personal Information</p>
		<p class="contenttext">We will not share, sell, rent, or trade your Personal Information with other parties except as provided below: </p>
		<p class="contenttext"><strong>We may share your information with Authorized Third Party Service Providers</strong>. We provide services and products through third parties. These "Third Party Service Providers" perform functions on our behalf, like sending out and distributing our administrative and promotional emails, SMS. We may share your Personal Information with such Service Providers to fulfill orders, deliver packages, send postal or email or SMS, administer contests or sweepstakes, remove repetitive information on customer lists, analyze data, provide marketing assistance, provide search results and links, process credit card payments, operate the Website, troubleshoot, and provide customer service. We may also collect personal information from individuals and companies ("Affiliates") with whom we have business relationships and may share your information with Service Providers to accomplish our administrative tasks. We encourage VMC third party service providers to adopt and post privacy policies. However, the use of your Personal Information by such parties is governed by the privacy policies of such parties and is not subject to our control. </p>
		<p class="contenttext"><strong>We may remarket your information</strong>. Remarketing is a way for us to connect with users, based upon your past interactions with VMC. We may reconnect with you through Third-party marketing via Email, SMS etc. Should you not want us to contact you please unsubscribe to VMC by sending mail to support@vmc.in, Please indicate your name, address email address and phone number, and what information you would not like us to use your information for remarketing purposes.  This information is used only for remarketing purposes and will not be used by them for any other purpose.</p>
		<p class="contenttext"><strong>We may share your information in a Business Transfer</strong>. As with any other business, we could merge with, or be acquired by another company. If this occurs, the successor company would acquire the information we maintain, including Personal Information. However, Personal Information would remain subject to this Privacy Policy. </p>
		<p class="contenttext">We may share your information for our Protection and the Protection of Others. We reserve the right to disclose your Personal Information as required by law and when we believe that disclosure is necessary to protect our rights and/or comply with a judicial proceeding, court order, or legal process served on our Website; enforce or apply this Privacy Policy, our Website Terms of Use or other agreements; or protect the rights, property or safety of the Website, its Users or others.</p>
		<p class="contentsubhead">4. Release of Non-Personal Information</p>
		<p class="contenttext">We may disclose or share Non-Personal Information with Partners, Affiliates and Advertisers. For example, we may share aggregated demographic information (which does not include any Personal Information) with "Third Party Advertisers" or "Third Party Advertising Companies" and other parties.</p>
		<p class="contenttext">We use Third Party Advertising Companies to serve ads when you visit our Website. We also use Third Party Service Providers to track and analyze Non-Personally Identifiable usage and volume statistical information from our Users to administer our Website and constantly improve its quality. We may also publish this information for promotional purposes or as a representative audience for Advertisers. Please note that this is not Personal Information, only general summaries of the activities of our Users. Such data is collected on our behalf, and is owned and used by us.</p>
		<p class="contentsubhead">5. Updating and Correcting Information</p>
		<p class="contenttext">You may change any of your Personal Information by logging into your account and accessing the "my account" section of the site.</p>
		<p class="contenttext">We encourage you to promptly update your Personal Information if it changes. You may ask to have the information on your account deleted or removed; however, because we keep track of past transactions, you cannot delete information associated with past transactions on the Website. In addition, it may be impossible for us to completely delete all of your information because we periodically backup information.</p>
		<p class="contenttext">We do not store your credit card details, you will be asked for credit card number every time you make a purchase.</p>
		<p class="contentsubhead">6. Administrative Emails</p>
		<p class="contenttext">As a condition of purchase of our products and services, we will send you Administrative and Promotional emails. We will send you information regarding your account activity and purchases as well as updates about our products and promotional offers. You cannot opt-out of Administrative Emails. </p>
		<p class="contentsubhead">7. Security of Information</p>
		<p class="contenttext">We take security seriously and take numerous precautions to protect the security of Personal Information and any data related to you or your business. You can access your Personal Information and entitled data on our Website through a password and your email address. This password is encrypted. We recommend that you do not share your password with anyone. In addition, your Personal Information resides on a secure server that only selected personnel and contractors have access to. We encrypt certain sensitive information using Secure Socket Layer (SSL) technology to ensure that your Personal Information is safe as it is transmitted to us. </p>
		<p class="contenttext">Unfortunately, no data transmission over the Internet or any wireless network can be guaranteed to be 100% secure. As a result, while we employ commercially reasonable security measures to protect data and seek to partner with companies which do the same, we cannot guarantee the security of any information transmitted to or from the Website, and are not responsible for the actions of any third parties that may receive any such information. </p>
		<p class="contentsubhead">8. Data Tracking</p>
		<p class="contenttext"><strong>Cookies</strong>. To facilitate and customize your experience with the Website, we store cookies on your computer. A cookie is a small text file that is stored on a Users computer for record-keeping purposes which contains information about that User. We use cookies to save you time while using the Website, remind us who you are, and track and target User interests in order to provide a customized experience. Cookies also allow us to collect Non-Personal Information from you, like which pages you visited and what links you clicked on. Use of this information helps us to create a more user-friendly experience for all visitors. In addition, we may use Third Party Advertising Companies to display advertisements on our Website. As part of their service, they may place separate cookies on your computer. We have no access to or control over these cookies. This Privacy Policy covers the use of cookies by our Website only and does not cover the use of cookies by any Advertiser. Most browsers automatically accept cookies, but you may be able to modify your browser settings to decline cookies. Please note that if you decline or delete these cookies, some parts of the Website may not work properly.</p>
		<p class="contentsubhead">9. Privacy Policies of Third Party Websites</p>
		<p class="contenttext">This Privacy Policy only addresses the use and disclosure of information we collect from you on www.vmc.in. Other websites that may be accessible through this Website have their own privacy policies and data collection, use and disclosure practices. If you link to any such website, we urge you review the websites privacy policy. We are not responsible for the policies or practices of third parties. </p>
		<p class="contentsubhead">10. Your Consent</p>
		<p class="contenttext">By submitting your information you consent to the use of that information set out in this privacy policy.</p>
		<p class="contenttext">We reserve the right to change our policy from time to time. If we change our policy we will post changes on this page and may place notices on other pages of the website and may place notice in tour account or email you. Continued use of the services offered by us will signify that you agree to any such changes.</p>
		<p class="contentsubhead">11. Miscellaneous Privacy Issues</p>
		<p class="contenttext"><strong>Children</strong>. Minors under the age of 18 may not use the Website. We do not knowingly collect personal information from anyone under the age of 18, and no part of the Website is designed to attract anyone under the age of 18. VMC does not sell products for purchase by children.</p>
		<p class="contenttext"><strong>Public Areas</strong>. We may provide areas on our Website where you can publicly post information about yourself, can communicate with others such as discussion boards or blogs, or can review products, and submit media content. This information may be accessible by other consumers and companies and may appear on other websites or web searches, and therefore this information could be read, collected, and used by others. For example, if you post your email address along with a property review, you may receive unsolicited messages. We have no control over who reads your postings or what other users may do with the information you voluntarily post, so please use caution when posting any personal information. We do obtain consent from our users to post their name along with their reviews.</p>
		<p class="contentsubhead">12. Contacting Us</p>
		<p class="contenttext"><strong>Corporate Address</strong><br />	VMC Technologies Pvt. Ltd., B-58, Sector 65, Noida, UP-201301</p>
		<p class="contenttext"><strong>For Customers</strong><br />	For Support call:<span class="navtollfreeA">18004192202 </span>	</p>
	</div>
 </div>

<div class="column2"> 
<? $this->load->view('rightform')?>
</div>
</div>
</div>
